# Generated by Django 2.2.5 on 2022-01-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs_viz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
