# Generated by Django 2.2.5 on 2022-03-16 22:17

from django.db import migrations, models
import rs_viz.models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_viz', '0003_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='activated',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='document',
            field=models.FileField(upload_to='rs_viz/', validators=[rs_viz.models.validate_file_extension]),
        ),
    ]
